eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7043/eureka
    instance:
        instance-id: ${spring.application.name}:${random.int} #cada instancia terá um id distinto para registro no eureka server
server:
    port: 0
spring:
    application:
        name: pedidos-ms
    datasource:
        driver-class-name: org.h2.Driver
        password: root
        url: jdbc:h2:file:./pedidos/data/pedidoDB;DB_CLOSE_ON_EXIT=FALSE
        username: root
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
