eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7043/eureka

server:
    port: 7044

spring:
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
