eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7043/eureka
resilience4j:
    circuitbreaker:
        instances:
            atualizaPedido:
                minimumNumberOfCalls: 2
                slidingWindowSize: 3
                waitDurationInOpenState: 50s
server:
    port: 0
spring:
    application:
        name: pagamento-ms
    datasource:
        driver-class-name: org.h2.Driver
        password: root
        url: jdbc:h2:file:./pagamentos/data/pagamentoDB;DB_CLOSE_ON_EXIT=FALSE
        username: root
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
